# Generated by Django 6.1.1 on 2026-09-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_order_razorpay_order_id_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_grocery',
            field=models.BooleanField(default=False),
        ),
    ]
