# Generated by Django 6.1.1 on 2026-09-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_item_is_grocery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(help_text='Enter ingredients separated by commas')),
                ('cooking_time', models.PositiveIntegerField(help_text='Cooking time in minutes')),
                ('instructions', models.TextField()),
                ('picture', models.URLField(blank=True, max_length=500)),
                ('vegetarian', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
